### ISSUE TITLE
exportable builds

### ISSUE THREAD

**Issue by pavelskipenes** [Sigevio/org.ntnu.svommer#2]
To be able to merge with https://github.com/ntnorg.ntnu.svommer the page needs to be exportable to a static site. This is because we use shared hosting and the only server software that is available is apache eg node will not be available. i18n does not support exporting to a static site.

**Comment by Sigevio** [comment]
Will start looking at possible solutions shortly.

**Comment by Sigevio** [comment]
Closed with #3
