### ISSUE TITLE
Missing admin login

### ISSUE THREAD

**Issue by pavelskipenes** [Sigevio/org.ntnu.svommer#4]

**Comment by pavelskipenes** [comment]
![image](https://user-images.githubusercontent.com/38912521/181765592-17c2cd81-2c9d-4f85-9c10-3a8a4417f290.png)
Yes admin dashboard is present but I ment having a login screen with username and password fields :smile: 

Can I suggest removing sections "web" and "members" and adding top level entries like "Profile", "Users", "Members" and "Web store". Also having number next to each tool (like notifications) on actions ready to be handled manually would be really cool e.g. new manual membership requests.

Also there should be some way to change password and log out.

**Comment by Sigevio** [comment]
Just set "isLoggedIn" to false in "AdminLayout.tsx"

**Comment by Sigevio** [comment]
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/92177978/181771760-342c4382-062c-45b9-89ad-81856b2f2cff.png">

**Comment by pavelskipenes** [comment]
> Just set "isLoggedIn" to false in "AdminLayout.tsx"
I see. Yeah, works fine!
